### ISSUE TITLE
Questions about changes for 60hz mains

### ISSUE THREAD

**Issue by mtnscott** [estechnical/reflowOvenController#1]
I have been studying the code trying to enable support for 60hz mains.  I have identified several locations in the code that require changes to support 120 zero crossings / sec.  It seems to me that your implementation is not correct with 83.333 for 60hz mains.

I am a bit stuck on the relationship between the timer ISR and the zero crossing handler.  On 50hz systems the timerISR is called 100 times for each mains zero crossing.  On 60hz systems this is not true.  I can change the timerISR to fire 100 times by setting the timer to 83us, unfortunately this introduces an error as the timer can only accept an integer and the actual number is 83.333

Do you have any suggestions on how to properly modify this code for 60hz.

It not clear how you manage the phase control and wave packet based on the relationship of timerTicks, phaseCounter, and Channel.next.  Would it be possible if you could explain your logic?

**Comment by mtnscott** [comment]
Sorry, I should have reviewed your code first, This question was suppose to be for 0xPIT who cloned your repository and then build from it.  For some reason I an unable to submit a issue to his repository and somehow ended up on yours.  Please ignore this questions.

**Comment by estechnical** [comment]
On 22/03/15 02:41, Scott Piette wrote:

> Sorry, I should have reviewed your code first, This question was
> suppose to be for 0xPIT who cloned your repository and then build from
> it. For some reason I an unable to submit a issue to his repository
> and somehow ended up on yours. Please ignore this questions.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/estechnical/reflowOvenController/issues/1#issuecomment-84502294.
> 
> No problem... Thanks.

## 

Ed Simmons
ed@estechnical.co.uk
www.estechnical.co.uk
