### ISSUE TITLE
pid and sample time

### ISSUE THREAD

**Issue by ariefadha** [estechnical/reflowOvenController#3]
what is your PID sampling time? is it 100ms?
and what is your temperature sampling time? is it 250ms?

can you address me to your code, that related to this?

thanks.

**Comment by estechnical** [comment]
The default period for the PID library is 100ms.

https://github.com/estechnical/reflowOvenController/blob/master/libraries/PID_v1/PID_v1.cpp#L32

The temperature sampling time is set here

https://github.com/estechnical/reflowOvenController/blob/master/ReflowController/ReflowController.ino#L24
